name: check code quality
on:
  push:
    branches:
      - master  

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: install
        run: python -m pip install black ruff isort mypy
      - name: Run formatters
        run: python -m black --check . && python -m isort --check .
      - name: Run linter
        run: python -m ruff .
      - name: Run static type cheker
        run: python -m mypy .
